name: Django CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: testsecretkey
      EMAIL_HOST_USER: test@example.com
      EMAIL_HOST_PASSWORD: testpassword

    steps:
    - name: 1️⃣ Checkout Code
      uses: actions/checkout@v4

    - name: 2️⃣ Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 3️⃣ Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: 4️⃣ Show Files (DEBUG)
      run: |
        ls -la

    - name: 5️⃣ Run Django Check
      run: |
        python manage.py check

    - name: 6️⃣ Migration Check
      run: |
        python manage.py makemigrations --check --dry-run